package generator

// DockerfileTemplate is the template for generating Dockerfiles
// Based on rancher/rancher package/Dockerfile-charts
const DockerfileTemplate = `# Generated by rancher-assets generator
# DO NOT EDIT - changes will be overwritten
#
# This Dockerfile defaults to DEV configuration (dev branches/commits).
# For PROD builds, override ARGs via --build-arg during docker build.

ARG BCI_VERSION={{.BciVersion}}
ARG VERSION=${VERSION}

# Build type: dev or prod (informational, for labels)
ARG BUILD_TYPE=dev

# Chart branch context - defaults to DEV branches
# Override these for prod builds using --build-arg
ARG CHART_BRANCH={{.DefaultChartsBranch}}
ARG PARTNER_BRANCH={{.DefaultPartnerBranch}}
ARG RKE2_BRANCH={{.DefaultRke2Branch}}

# Chart commit SHAs - defaults to DEV commits (from lock.yaml)
# Override these for prod builds using --build-arg
ARG CHART_COMMIT={{.ChartCommit}}
ARG PARTNER_COMMIT={{.PartnerCommit}}
ARG RKE2_COMMIT={{.Rke2Commit}}

# Runtime labels - provided by build
ARG GIT_COMMIT
ARG BUILD_DATE
ARG TARGET_BRANCH
ARG BUILD_URL

FROM registry.suse.com/bci/bci-base:${BCI_VERSION} AS builder
RUN zypper refresh && zypper -n install git-core

# Clone rancher-charts repository
FROM builder AS rancher-charts
ARG CHART_COMMIT
RUN mkdir -p /var/lib/rancher-data/local-catalogs/v2 && \
    git config --global url."https://github.com/rancher/".insteadOf https://git.rancher.io/ && \
    git init {{(index .ClusterRepos "charts").Path}} && \
    cd {{(index .ClusterRepos "charts").Path}} && \
    git remote add origin {{(index .ClusterRepos "charts").URL}} && \
    git fetch --depth 1 origin ${CHART_COMMIT} && \
    git checkout FETCH_HEAD

# Clone partner-charts repository
FROM builder AS partner-charts
ARG PARTNER_COMMIT
RUN mkdir -p /var/lib/rancher-data/local-catalogs/v2 && \
    git config --global url."https://github.com/rancher/".insteadOf https://git.rancher.io/ && \
    git init {{(index .ClusterRepos "partner").Path}} && \
    cd {{(index .ClusterRepos "partner").Path}} && \
    git remote add origin {{(index .ClusterRepos "partner").URL}} && \
    git fetch --depth 1 origin ${PARTNER_COMMIT} && \
    git checkout FETCH_HEAD

# Clone rke2-charts repository
FROM builder AS rke2-charts
ARG RKE2_COMMIT
RUN mkdir -p /var/lib/rancher-data/local-catalogs/v2 && \
    git config --global url."https://github.com/rancher/".insteadOf https://git.rancher.io/ && \
    git init {{(index .ClusterRepos "rke2").Path}} && \
    cd {{(index .ClusterRepos "rke2").Path}} && \
    git remote add origin {{(index .ClusterRepos "rke2").URL}} && \
    git fetch --depth 1 origin ${RKE2_COMMIT} && \
    git checkout FETCH_HEAD

# Consolidated charts image
FROM registry.suse.com/bci/bci-micro:${BCI_VERSION} AS charts

# Copy chart repositories
COPY --from=rancher-charts {{(index .ClusterRepos "charts").Path}} {{(index .ClusterRepos "charts").Path}}
COPY --from=partner-charts {{(index .ClusterRepos "partner").Path}} {{(index .ClusterRepos "partner").Path}}
COPY --from=rke2-charts {{(index .ClusterRepos "rke2").Path}} {{(index .ClusterRepos "rke2").Path}}

# Copy charts copy script
COPY package/copy-charts.sh /usr/local/bin/copy-charts
RUN chmod +x /usr/local/bin/copy-charts

# Store branch and commit metadata as ENV for runtime access
ARG CHART_BRANCH
ARG PARTNER_BRANCH
ARG RKE2_BRANCH
ARG CHART_COMMIT
ARG PARTNER_COMMIT
ARG RKE2_COMMIT

ARG BUILD_TYPE

ENV CHART_BRANCH=${CHART_BRANCH} \
    PARTNER_BRANCH=${PARTNER_BRANCH} \
    RKE2_BRANCH=${RKE2_BRANCH} \
    CHART_COMMIT=${CHART_COMMIT} \
    PARTNER_COMMIT=${PARTNER_COMMIT} \
    RKE2_COMMIT=${RKE2_COMMIT}

LABEL "io.artifacthub.package.logo-url"="https://raw.githubusercontent.com/rancher/ui/master/public/assets/images/logos/welcome-cow.svg" \
    "io.artifacthub.package.readme-url"="https://raw.githubusercontent.com/rancher/rancher/release/v2.6/README.md" \
    "org.opencontainers.image.description"="Rancher Charts {{.ChartMajor}}: bundled Helm charts for Rancher {{.RancherVersion}}" \
    "org.opencontainers.image.title"="Rancher Charts {{.ChartMajor}}" \
    "org.opencontainers.image.source"="https://github.com/rancher/rancher-assets" \
    "org.opencontainers.image.version"=${VERSION} \
    "org.opencontainers.image.revision"=${GIT_COMMIT} \
    "org.opencontainers.image.created"=${BUILD_DATE} \
    "org.opensuse.reference"=rancher/rancher-charts:${VERSION} \
    "io.rancher.target-branch"=${TARGET_BRANCH} \
    "io.rancher.build-url"=${BUILD_URL} \
    "io.rancher.build-type"=${BUILD_TYPE} \
    "io.rancher.charts.branch"=${CHART_BRANCH} \
    "io.rancher.charts.commit"=${CHART_COMMIT} \
    "io.rancher.partner.branch"=${PARTNER_BRANCH} \
    "io.rancher.partner.commit"=${PARTNER_COMMIT} \
    "io.rancher.rke2.branch"=${RKE2_BRANCH} \
    "io.rancher.rke2.commit"=${RKE2_COMMIT}

# Default command: copy charts to shared volume
CMD ["/usr/local/bin/copy-charts"]
`
