name: PR Builder Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 1-5' # Runs at 11:00 UTC Monday through Friday

permissions:
  contents: write
  id-token: write # required for OIDC -> Vault

jobs:
  bump-pr-builder:
    name: Bump Chart References
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/go1.26
    steps:
      - name: Read GitHub App Token from Vault
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        if: github.repository == 'rancher/rancher-assets'
        with:
          secrets: |
            github/token/rancher--rancher-assets--contents--write token | GH_APP_TOKEN

      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          token: ${{ env.GH_APP_TOKEN }}
          persist-credentials: true

      - name: Run bump-pr-builder
        if: github.repository == 'rancher/rancher-assets'
        env:
          CI: true
          GH_TOKEN: ${{ env.GH_APP_TOKEN }}
          APP_USER: "eio-github-actions-power-enhancer[bot]"
          SOURCE_REPO: ${{ github.repository }}
          REPO_DIR: ${{ github.workspace }}
        run: ./.github/workflows/bump-pr-builder/run-gha.sh
