name: PR CI

permissions:
  contents: read

on:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/go1.26
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run golangci-lint
        run: golangci-lint run ./...

  test:
    name: Test & Verify
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/go1.26
    env:
      CI: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Run tests
        run: ./scripts/test

      - name: Run generate
        run: make generate

      - name: Verify generated files are committed
        run: ./scripts/verify
