name: Vault Debug Test
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Get GitHub token for rancher/rancher PRs"
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            github/token/rancher--rancher--pull_requests--write token | GH_TOKEN
