name: Vault Debug Test
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        run: |
          echo "role would be: ${{ github.event.repository.name }}"
          echo "path would be: ${{ github.repository_owner }}"

      - name: Debug OIDC token
        run: |
          curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/rancher" \
            | jq -r '.value' | cut -d. -f2 | base64 -d | jq .

      - name: "Read vault secrets"
        uses: rancher-eio/read-vault-secrets@0da85151ad1f19ed7986c41587e45aac1ace74b6 # v3
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/github/pr-actions-write-app/credentials appId | APP_ID
